version: '2'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=peatio_development
      - MYSQL_USER=root
    ports:
      - '3306:3306'

  redis:
    image: redis
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq

  nginx:
    build: containers/nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - rails

  rails:
    build: containers/rails
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root@mysql:3306
      URL_HOST: localhost
      REDIS_URL: redis://redis:6379
    volumes:
      - '../peatio:/usr/src/app'
    links:
      - mysql
      - redis
      - rabbitmq
